### ISSUE TITLE
ValueError: Cannot feed value of shape (3, 3, 512, 256) for Tensor 'G_synthesis/64x64/Conv0_up/weight/new_value:0', which has shape '(3, 3, 512, 512)'

### ISSUE THREAD

**Issue by eluzzi5** [dvschultz/ml-art-colabs#7]
Hi there, I'm getting the following error when trying to run this notebook:

Traceback (most recent call last):
  File "train.py", line 645, in <module>
    main()
  File "train.py", line 637, in main
    run_training(**vars(args))
  File "train.py", line 522, in run_training
    training_loop.training_loop(**training_options)
  File "/content/drive/My Drive/colab-sg2-ada/stylegan2-ada/training/training_loop.py", line 129, in training_loop
    G.copy_vars_from(rG)
  File "/content/drive/My Drive/colab-sg2-ada/stylegan2-ada/dnnlib/tflib/network.py", line 512, in copy_vars_from
    self._components[name].copy_vars_from(src_comp)
  File "/content/drive/My Drive/colab-sg2-ada/stylegan2-ada/dnnlib/tflib/network.py", line 509, in copy_vars_from
    self.copy_own_vars_from(src_net)
  File "/content/drive/My Drive/colab-sg2-ada/stylegan2-ada/dnnlib/tflib/network.py", line 482, in copy_own_vars_from
    tfutil.set_vars({self._get_vars()[name]: value for name, value in value_dict.items() if name in self._get_vars()})
  File "/content/drive/My Drive/colab-sg2-ada/stylegan2-ada/dnnlib/tflib/tfutil.py", line 227, in set_vars
    run(ops, feed_dict)
  File "/content/drive/My Drive/colab-sg2-ada/stylegan2-ada/dnnlib/tflib/tfutil.py", line 33, in run
    return tf.get_default_session().run(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1156, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (3, 3, 512, 256) for Tensor 'G_synthesis/64x64/Conv0_up/weight/new_value:0', which has shape '(3, 3, 512, 512)'

Can you please help me debug this? Since it is coming from the files I didn't write and I am a beginner, I am not sure how to tackle this. Thank you!

**Comment by eluzzi5** [comment]
Update: I changed the following line of code: 

resume_from = "ffhq256"
to
resume_from = "ffhq512"

and that seemed to work. I am not sure why, I guess it was expecting 512 resolution.
